Initial vault extension creation
scandipwa/vault-graphql pull request #1
Opened 2021-02-03 11:01 UTC by AleksandrsKondratjevs

2021-02-11 11:01 UTC, yeegor requested changes
Minor changes required

2021-02-11 11:01 UTC, yeegor commented on src/component/VaultStorage/VaultStorage.component.js
> +            </>
Doesn't ESLint shout at this indentation?

2021-02-11 11:01 UTC, yeegor commented on src/plugin/App.plugin.js
> +};
Please try to do it without importing anything from thee store. Maybe the store can be intercepted before rendering into the context providers? Sometimes direct imports from the store break the application having some irregular circumstances.

2021-02-11 11:01 UTC, yeegor commented on src/plugin/CheckoutBillingContainer.plugin.js
> +    ] = args;
You can do that directly in the arguments section:
```js
export const mapStateToProps = ([{
    VaultReducer: { public_hash }
}], callback) => ...
```

2021-02-11 11:01 UTC, yeegor commented on src/plugin/CheckoutPaymentsContainer.plugin.js
> +    ] = args;
same here as above

2021-02-11 11:01 UTC, yeegor commented on src/store/Vault/Vault.dispatcher.js
> +                dispatch(showNotification('success', __('Stored Payment Method was successfully removed!')));
"is successfully removed" would be better. Or "has been removed successfully". "Was" tense implies action's incompleteness.

2021-02-11 13:23 UTC, AleksandrsKondratjevs commented on src/store/Vault/Vault.dispatcher.js
> +                dispatch(showNotification('success', __('Stored Payment Method was successfully removed!')));
Hey! I guess I just took this message from default magento (Luma theme). Should I still change it?

2021-02-25 13:16 UTC, yeegor approved these changes
Legit.

2021-02-25 13:16 UTC, merged